kind: Namespace
apiVersion: v1
metadata:
  name: hello-universe

---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    name: hello-universe
  name: hello-universe
  namespace: hello-universe
data:
  ADD_FUN: YEAH

---
apiVersion: v1
kind: Secret
metadata:
  labels:
    name: hello-universe
  name: hello-universe
  namespace: hello-universe
data:
  ADD_FUN: WUVBSAo=

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: hello-universe
  name: hello-universe
spec:
  replicas: 2
  template:
    spec:
      containers:
        - image: local/hello-universe:v2
          name: hello-universe
          imagePullPolicy: IfNotPresent
          ports:
            - protocol: TCP
              name: pythonport
              containerPort: 9999
          env:
            - name: ADD_WORK
              value: NOPE
          envFrom:
            - configMapRef:
                name: hello-universe
            # - secretRef:
            #     name: hello-universe
          livenessProbe:
            initialDelaySeconds: 5
            tcpSocket:
              port: pythonport
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: "/"
              port: pythonport
            timeoutSeconds: 10
            periodSeconds: 5
            successThreshold: 1
            initialDelaySeconds: 5
            failureThreshold: 2
          resources:
            requests:
              cpu: "0.10"
              memory: 100M
            limits:
              cpu: "0.20"
              memory: 200M
      nodeSelector:
        kubernetes.io/hostname: minikube
    metadata:
      labels:
        name: hello-universe
        version: v1
  selector:
    matchLabels:
      name: hello-universe

---
kind: Service
apiVersion: v1
metadata:
  name: hello-universe
  namespace: hello-universe
spec:
  type: NodePort
  ports:
    - protocol: TCP
      targetPort: pythonport
      port: 80
      nodePort: 32000
  selector:
    name: hello-universe
