apiVersion: skaffold/v1beta15
kind: Config
build:
  artifacts:
    - image: local/hello-universe
      context: hello-universe-flask-app
  tagPolicy:
    # sha256: {}
    dateTime:
      timezone: Local
deploy:
  kubectl:
    manifests:
      - "k8s/*"
    # - k8s/hello-universe.yaml
